#162699940  allow users edit an article
andela/ah-frontend-thor pull request #38
Opened 2018-12-19 17:43 UTC by joshNic

#### What does this PR do?
- Allows a user to edit an article
#### Description of Task to be completed?
- Create the EditArticle component which is rendered when the user wants to edit the article
- Create tests for the component
- Create the PublishedArticles component which renders the articles owned by the user who is logged in.
- Create tests for the PublishArticles component 
#### How should this be manually tested?
- clone the repo in your local environment with `git clone https://github.com/andela/ah-frontend-thor.git`
- run `yarn` or `npm install` to install dependencies
- run `yarn start:dev` to launch the app
- run `yarn test -u` to run the tests
#### What are the relevant pivotal tracker stories?
#162699940
#### Screenshots (if appropriate)
<img width="712" alt="screen shot 2018-12-19 at 20 40 31" src="https://user-images.githubusercontent.com/12236213/50237663-8752af00-03ce-11e9-820f-974e1e329541.png">
<img width="1170" alt="screen shot 2018-12-19 at 20 40 46" src="https://user-images.githubusercontent.com/12236213/50237665-87eb4580-03ce-11e9-94b9-523a1a2ef817.png">
<img width="1174" alt="screen shot 2018-12-19 at 20 41 00" src="https://user-images.githubusercontent.com/12236213/50237666-8883dc00-03ce-11e9-89bc-89e23ffbdb42.png">
<img width="614" alt="screen shot 2018-12-19 at 20 41 16" src="https://user-images.githubusercontent.com/12236213/50237667-89b50900-03ce-11e9-8116-99d5bb77688c.png">

2018-12-19 19:26 UTC, bozicschucky requested changes

2018-12-19 19:26 UTC, bozicschucky commented on src/actions/articleActions.js
> +      console.log(
remove all the console logs.

2018-12-19 19:26 UTC, bozicschucky commented on src/containers/Profile/PublishedArticles.jsx
> +            <a href="article.html">
this href should be removed since it will return a 404.

2018-12-19 19:26 UTC, bozicschucky commented on tests/integerationTests/PublishedArticles.test.jsx
> +import "babel-polyfill";
Why are you importing this package  and It is not used anywhere.

2018-12-19 19:26 UTC, bozicschucky commented on tests/integerationTests/EditArticle.test.jsx
> +  // it("should", () => {
commented out code.

2018-12-20 17:14 UTC, bozicschucky approved these changes

2018-12-20 17:24 UTC, johnkegz commented on src/components/article/PostArticle.jsx
> +// import {  } from "../../actions/articleActions";
@joshNic, remove commented out code.

2018-12-20 17:24 UTC, johnkegz commented on src/reducers/rootReducer.js
> +// import articleReducer from "./articleReducer";
@joshNic remove commented out code

2018-12-21 03:32 UTC, joshNic commented on src/components/article/PostArticle.jsx
> +// import {  } from "../../actions/articleActions";
@johnkegz I have worked on this

2018-12-21 03:32 UTC, joshNic commented on src/reducers/rootReducer.js
> +// import articleReducer from "./articleReducer";
@johnkegz I have worked on this

2018-12-21 04:27 UTC, shakirandagire commented on src/components/article/PostArticle.jsx
> +export { PostArticle };
What is the significance of this export

2018-12-21 04:27 UTC, shakirandagire commented on src/reducers/articleReducer.js
> +};
Could you add a single line at the end of the file

2018-12-21 04:27 UTC, shakirandagire commented on tests/integerationTests/PostArticle.test.jsx
> +  // const providerr = shallow(<ConnectedPostArticle store={store} match={{ params: { } }} />);
Could you remove commented out code from the file

2018-12-21 04:27 UTC, shakirandagire commented on tests/integerationTests/PostArticle.test.jsx
> +  // const providerr = shallow(<ConnectedPostArticle store={store} match={{ params: { } }} />);
Could you remove commented out code

2018-12-21 04:27 UTC, shakirandagire commented on tests/integerationTests/PostArticle.test.jsx
> +});
Add an extra line at the end of the file

2018-12-21 04:27 UTC, shakirandagire commented on tests/integerationTests/PublishedArticles.test.jsx
> +  document
Is this code required in the test

2018-12-21 04:27 UTC, shakirandagire commented on tests/unitTests/ArticleAction.test.jsx
> +describe("SocialLogin action creators", () => {
Could you rename all the describe to indicate the actual tests you are working on

2018-12-21 04:27 UTC, shakirandagire commented on tests/unitTests/ArticleReducer.test.jsx
> +// import { updateArticleReducer } from "../../src/reducers/articleReducer";
Could you remove commented out code

2018-12-21 04:27 UTC, shakirandagire commented on tests/unitTests/ArticleReducer.test.jsx
>  describe("socialLoginReducer", () => {
Could you rename the describe to indicate the tests you are working on

2018-12-21 06:23 UTC, joshNic commented on src/components/article/PostArticle.jsx
> +export { PostArticle };
Wanted to test it in isolation without it being connected to the store so I exported it as a named component

2018-12-21 06:24 UTC, joshNic commented on tests/integerationTests/PostArticle.test.jsx
> +  // const providerr = shallow(<ConnectedPostArticle store={store} match={{ params: { } }} />);
@shakirandagire I have worked on this

2018-12-21 06:24 UTC, joshNic commented on tests/integerationTests/PostArticle.test.jsx
> +});
@shakirandagire  I have worked on this

2018-12-21 06:26 UTC, joshNic commented on tests/integerationTests/PublishedArticles.test.jsx
> +  document
@shakirandagire yes only that I had an EditArticle component but after refactoring I used the same Component to do both creating and updating

2018-12-21 06:26 UTC, joshNic commented on tests/unitTests/ArticleAction.test.jsx
> +describe("SocialLogin action creators", () => {
@shakirandagire I have worked on this

2018-12-21 06:26 UTC, joshNic commented on tests/unitTests/ArticleReducer.test.jsx
> +// import { updateArticleReducer } from "../../src/reducers/articleReducer";
@shakirandagire I have worked on this

2018-12-21 06:26 UTC, joshNic commented on tests/unitTests/ArticleReducer.test.jsx
>  describe("socialLoginReducer", () => {
@shakirandagire I have worked on this

2018-12-21 07:09 UTC, shakirandagire commented on src/components/article/PostArticle.jsx
> +export { PostArticle };
Could you clarify more on that

2018-12-21 07:30 UTC, shakirandagire commented on tests/integerationTests/PublishedArticles.test.jsx
> +  document
Alright then

2018-12-21 07:44 UTC, shakirandagire approved these changes

2018-12-21 07:44 UTC, shakirandagire commented on src/components/article/PostArticle.jsx
> +export { PostArticle };
Alright then

2018-12-21 07:45 UTC, merged