Ch setup redux 161382342
andela/ah-frontend-thor pull request #4
Opened 2018-11-27 15:16 UTC by bozicschucky

#### What does this PR do?
Sets up Redux and the Redux dev tools of the App.
#### Description of Task to be completed?
- Sets up the Redux library to help in state management of the App.
#### How should this be manually tested?
- Git `clone this branch`.
- Git `install the dependencies using Yarn install`
- Run the project locally using`yarn start:dev`
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
161382342

2018-11-28 12:33 UTC, johnkegz reviewed
@bozicschucky, wait for Cedric's PR to be merged and then rebase because he has reconfigured hound

2018-11-28 12:40 UTC, emukungu approved these changes

2018-11-28 12:41 UTC, joshNic approved these changes

2018-11-28 12:43 UTC, emukungu requested changes
Squash commits

2018-11-28 13:29 UTC, shakirandagire commented
@bozicschucky Could you resolve the merge conflicts and squash commits.
Could you rename the pull request name to follow these conventions:#[STORY_ID] [Story description]

2018-11-28 13:43 UTC, cdvx commented on src/store.js
> +const intialState = {};
@bozicschucky The fix has been merged into develop,  try rebasing so that this `'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).` does not show up

2018-11-28 16:32 UTC, johnkegz approved these changes

2018-11-29 07:57 UTC, bozicschucky commented
@shakirandagire I have worked on the feedback. Review thanks.

2018-11-30 07:42 UTC, joshNic requested changes
@bozicschucky please could you try to fix the codeclimate issues (hint try to at least write a dummy test for your code) and also delete the .hound.yaml file because it is no longer needed.

2018-11-30 11:31 UTC, cdvx approved these changes
LGTM 👍🏾

2018-11-30 13:59 UTC, emukungu commented
@chucky, why is some of your work commented out. When we rebase, should we remove it?

2018-11-30 14:01 UTC, joshNic approved these changes

2018-11-30 14:01 UTC, bozicschucky commented
@emukungu Yeah you should remove it since it was part of the boilerplate code.

2018-11-30 14:29 UTC, emukungu approved these changes

2018-11-30 14:57 UTC, merged